// Generated by scripts/policy-content.mjs. The five policy documents, in reading order.
export const POLICY_LINKS = [
  {
    "route": "/terms",
    "title": "Terms of Use"
  },
  {
    "route": "/privacy",
    "title": "Privacy Policy"
  },
  {
    "route": "/provider-terms",
    "title": "Provider Terms"
  },
  {
    "route": "/billing-disclosures",
    "title": "Billing Disclosures"
  },
  {
    "route": "/matching-standards",
    "title": "Matching Community Standards"
  }
] as const;
