// Demo / preview data. Shown ONLY when DEMO_MODE=1 (a private preview build),
// never on the live site. This lets the founder see a fully populated site.
// To remove the whole preview: delete this file and the `DEMO` branches that
// import from it (grep for "demo-data"). Nothing here is real.

export const DEMO = process.env.DEMO_MODE === "1";

type DemoEvent = {
  id: string;
  event_name: string;
  event_type: string;
  city: string;
  state: string;
  venue: string | null;
  address: string | null;
  description: string | null;
  event_date: string | null;
  end_date: string | null;
  price: string | null;
  registration_url: string | null;
  host: string | null;
  day_time: string | null;
  frequency: string | null;
  beginner_friendly: boolean | null;
  confirmed_active_at: string | null;
  tier: string;
  created_at: string;
};

const CA = "2026-06-01T00:00:00Z"; // confirmed-active stamp (recent)
const ON = "2026-01-01T00:00:00Z"; // created_at

export const demoEvents: DemoEvent[] = [
  { id: "demo-e1", event_name: "Scottsdale Morning Mahjong", event_type: "open_play", city: "Scottsdale", state: "AZ", venue: "Civic Center", address: null, description: "Friendly weekly open play. All levels welcome, bring your card.", event_date: null, end_date: null, price: "Free", registration_url: null, host: "Desert Tiles Club", day_time: "Wednesdays 10am", frequency: "weekly", beginner_friendly: true, confirmed_active_at: CA, tier: "free", created_at: ON },
  { id: "demo-e2", event_name: "Scottsdale Spring League", event_type: "league", city: "Scottsdale", state: "AZ", venue: "Civic Center", address: null, description: "Spring season league play, eight weeks, prizes for top tables.", event_date: null, end_date: null, price: "Free", registration_url: null, host: "Desert Tiles Club", day_time: "Thursdays 6pm", frequency: "weekly", beginner_friendly: false, confirmed_active_at: CA, tier: "free", created_at: ON },
  { id: "demo-e3", event_name: "Arizona Desert Classic", event_type: "tournament", city: "Phoenix", state: "AZ", venue: "Phoenix Convention Center", address: null, description: "Annual one-day tournament. NMJL rules, lunch included.", event_date: "2026-10-03", end_date: null, price: "$60", registration_url: "https://example.com", host: "AZ Mahjong Association", day_time: null, frequency: "once", beginner_friendly: true, confirmed_active_at: null, tier: "free", created_at: ON },
  { id: "demo-e4", event_name: "Sedona Fall Mahjong Retreat", event_type: "retreat", city: "Sedona", state: "AZ", venue: "Enchantment Resort", address: null, description: "Three-day retreat in the red rocks. All levels. Lodging and meals included.", event_date: "2026-10-15", end_date: "2026-10-18", price: "$395", registration_url: "https://example.com", host: "Red Rock Retreats", day_time: null, frequency: "multi_day", beginner_friendly: true, confirmed_active_at: null, tier: "free", created_at: ON },
  { id: "demo-e5", event_name: "Boca Raton Sunday Morning Mahj", event_type: "open_play", city: "Boca Raton", state: "FL", venue: "Boca Raton JCC", address: null, description: "Weekly Sunday morning open play. Intermediate and advanced. Coffee provided.", event_date: null, end_date: null, price: "$5 suggested donation", registration_url: null, host: "Boca Mahj Circle", day_time: "Sundays 9am", frequency: "weekly", beginner_friendly: false, confirmed_active_at: CA, tier: "free", created_at: ON },
  { id: "demo-e6", event_name: "Naples Snowbird Open Play", event_type: "open_play", city: "Naples", state: "FL", venue: "Naples Community Center", address: null, description: "Seasonal open play for winter residents. Newcomers paired with regulars.", event_date: null, end_date: null, price: "Free", registration_url: null, host: "Gulf Coast Mahjong", day_time: "Tuesdays 1pm", frequency: "weekly", beginner_friendly: true, confirmed_active_at: CA, tier: "free", created_at: ON },
  { id: "demo-e7", event_name: "South Florida Championship", event_type: "tournament", city: "Fort Lauderdale", state: "FL", venue: "Marriott Harbor Beach", address: null, description: "Two-day championship with cash prizes. Advance registration required.", event_date: "2026-11-07", end_date: "2026-11-08", price: "$95", registration_url: "https://example.com", host: "Sunshine Mahjong League", day_time: null, frequency: "once", beginner_friendly: false, confirmed_active_at: null, tier: "free", created_at: ON },
  { id: "demo-e8", event_name: "Dallas Tuesday Tiles", event_type: "open_play", city: "Dallas", state: "TX", venue: "Preston Hollow Clubhouse", address: null, description: "Casual weekly game. Beginners welcome, lessons before play.", event_date: null, end_date: null, price: "Free", registration_url: null, host: "Big D Mahjong", day_time: "Tuesdays 10am", frequency: "weekly", beginner_friendly: true, confirmed_active_at: CA, tier: "free", created_at: ON },
  { id: "demo-e9", event_name: "Lone Star Mahjong Tournament", event_type: "tournament", city: "Austin", state: "TX", venue: "Austin Convention Center", address: null, description: "Statewide tournament, all skill brackets. Proceeds to local charities.", event_date: "2026-09-12", end_date: null, price: "$50", registration_url: "https://example.com", host: "Texas Mahjong Society", day_time: null, frequency: "once", beginner_friendly: true, confirmed_active_at: null, tier: "free", created_at: ON },
  { id: "demo-e10", event_name: "Houston Heights League", event_type: "league", city: "Houston", state: "TX", venue: "Heights Community Hall", address: null, description: "Ten-week competitive league with a season finale.", event_date: null, end_date: null, price: "$40 season", registration_url: null, host: "Bayou Tiles", day_time: "Mondays 6:30pm", frequency: "weekly", beginner_friendly: false, confirmed_active_at: CA, tier: "free", created_at: ON },
  { id: "demo-e11", event_name: "Manhattan Lunchtime Mahjong", event_type: "open_play", city: "New York", state: "NY", venue: "92nd Street Y", address: null, description: "Midtown weekday game for working players. Drop in on your lunch break.", event_date: null, end_date: null, price: "$10", registration_url: null, host: "NYC Mahjong Collective", day_time: "Fridays 12pm", frequency: "weekly", beginner_friendly: false, confirmed_active_at: CA, tier: "free", created_at: ON },
  { id: "demo-e12", event_name: "Long Island Charity Classic", event_type: "tournament", city: "Garden City", state: "NY", venue: "Garden City Hotel", address: null, description: "Annual charity tournament. Raffle, lunch, and prizes.", event_date: "2026-12-05", end_date: null, price: "$75", registration_url: "https://example.com", host: "LI Mahjong Friends", day_time: null, frequency: "once", beginner_friendly: true, confirmed_active_at: null, tier: "free", created_at: ON },
  { id: "demo-e13", event_name: "Palm Springs Mahjong Getaway", event_type: "retreat", city: "Palm Springs", state: "CA", venue: "Parker Palm Springs", address: null, description: "Long-weekend desert retreat. Pool, play, and pampering. Limited to 36 players.", event_date: "2026-11-13", end_date: "2026-11-16", price: "$650 all-inclusive", registration_url: "https://example.com", host: "West Coast Mahj Retreats", day_time: null, frequency: "multi_day", beginner_friendly: true, confirmed_active_at: null, tier: "free", created_at: ON },
  { id: "demo-e14", event_name: "Bay Area Beginners Circle", event_type: "class", city: "San Mateo", state: "CA", venue: "Peninsula JCC", address: null, description: "Six-week beginner class. Learn the card, the rules, and the etiquette.", event_date: null, end_date: null, price: "$120 series", registration_url: "https://example.com", host: "Golden Gate Mahjong", day_time: "Saturdays 11am", frequency: "weekly", beginner_friendly: true, confirmed_active_at: CA, tier: "free", created_at: ON },
  { id: "demo-e15", event_name: "Caribbean Mahjong Cruise", event_type: "retreat", city: "Miami", state: "FL", venue: "Royal Caribbean, Symphony of the Seas", address: null, description: "Seven-night organized mahjong cruise. Daily play, lessons, and tournaments at sea.", event_date: "2027-01-17", end_date: "2027-01-24", price: "From $1,450", registration_url: "https://example.com", host: "Mahjong at Sea", day_time: null, frequency: "multi_day", beginner_friendly: true, confirmed_active_at: null, tier: "free", created_at: ON },
  { id: "demo-e16", event_name: "Chicago North Shore Open Play", event_type: "open_play", city: "Evanston", state: "IL", venue: "Levy Senior Center", address: null, description: "Weekly North Shore game. Friendly, social, all levels.", event_date: null, end_date: null, price: "Free", registration_url: null, host: "North Shore Mahjong", day_time: "Wednesdays 1pm", frequency: "weekly", beginner_friendly: true, confirmed_active_at: CA, tier: "free", created_at: ON },
  { id: "demo-e17", event_name: "Atlanta Spring Slam", event_type: "tournament", city: "Atlanta", state: "GA", venue: "Cobb Galleria", address: null, description: "One-day spring tournament with a beginner bracket.", event_date: "2027-03-14", end_date: null, price: "$55", registration_url: "https://example.com", host: "Peach State Mahjong", day_time: null, frequency: "once", beginner_friendly: true, confirmed_active_at: null, tier: "free", created_at: ON },
  { id: "demo-e18", event_name: "Denver Mile-High Mahjong", event_type: "open_play", city: "Denver", state: "CO", venue: "Cherry Creek Library", address: null, description: "Twice-monthly open play downtown. Newcomers always welcome.", event_date: null, end_date: null, price: "Free", registration_url: null, host: "Rocky Mountain Tiles", day_time: "1st and 3rd Mondays 6pm", frequency: "biweekly", beginner_friendly: true, confirmed_active_at: CA, tier: "free", created_at: ON },
  { id: "demo-e19", event_name: "San Antonio Riverwalk Open Play", event_type: "open_play", city: "San Antonio", state: "TX", venue: "Central Library", address: null, description: "Relaxed weekly game downtown. All levels welcome.", event_date: null, end_date: null, price: "Free", registration_url: null, host: "Alamo City Mahjong", day_time: "Thursdays 1pm", frequency: "weekly", beginner_friendly: true, confirmed_active_at: CA, tier: "free", created_at: ON },
  { id: "demo-e20", event_name: "Houston Summer Slam", event_type: "tournament", city: "Houston", state: "TX", venue: "Marriott Westchase", address: null, description: "One-day summer tournament, beginner and open brackets.", event_date: "2026-08-22", end_date: null, price: "$45", registration_url: "https://example.com", host: "Bayou Tiles", day_time: null, frequency: "once", beginner_friendly: true, confirmed_active_at: null, tier: "free", created_at: ON },
  { id: "demo-e21", event_name: "The Villages Daily Mahjong", event_type: "open_play", city: "The Villages", state: "FL", venue: "Laurel Manor Rec Center", address: null, description: "Daily drop-in games for residents and guests.", event_date: null, end_date: null, price: "Free", registration_url: null, host: "Villages Mahjong Club", day_time: "Weekdays 9am", frequency: "weekly", beginner_friendly: true, confirmed_active_at: CA, tier: "free", created_at: ON },
  { id: "demo-e22", event_name: "Sarasota Bayfront League", event_type: "league", city: "Sarasota", state: "FL", venue: "Selby Library", address: null, description: "Twelve-week league with end-of-season luncheon.", event_date: null, end_date: null, price: "$35 season", registration_url: null, host: "Suncoast Mahjong", day_time: "Wednesdays 6pm", frequency: "weekly", beginner_friendly: false, confirmed_active_at: CA, tier: "free", created_at: ON },
  { id: "demo-e23", event_name: "Los Angeles Westside Open Play", event_type: "open_play", city: "Los Angeles", state: "CA", venue: "Westwood Rec Center", address: null, description: "Weekly Westside game, friendly and social.", event_date: null, end_date: null, price: "Free", registration_url: null, host: "LA Mahjong Collective", day_time: "Mondays 10am", frequency: "weekly", beginner_friendly: true, confirmed_active_at: CA, tier: "free", created_at: ON },
  { id: "demo-e24", event_name: "San Diego Seaside Tournament", event_type: "tournament", city: "San Diego", state: "CA", venue: "Town and Country Resort", address: null, description: "Two-day coastal tournament with prizes and a welcome reception.", event_date: "2026-10-24", end_date: "2026-10-25", price: "$85", registration_url: "https://example.com", host: "SoCal Mahjong League", day_time: null, frequency: "once", beginner_friendly: false, confirmed_active_at: null, tier: "free", created_at: ON },
  { id: "demo-e25", event_name: "Brooklyn Brownstone Mahjong", event_type: "open_play", city: "Brooklyn", state: "NY", venue: "Park Slope Library", address: null, description: "Cozy weekly game in Park Slope. Beginners paired with mentors.", event_date: null, end_date: null, price: "Free", registration_url: null, host: "Brooklyn Mahjong", day_time: "Saturdays 2pm", frequency: "weekly", beginner_friendly: true, confirmed_active_at: CA, tier: "free", created_at: ON },
  { id: "demo-e26", event_name: "Boston Back Bay Open Play", event_type: "open_play", city: "Boston", state: "MA", venue: "Boston Public Library", address: null, description: "Weekly downtown game, all levels welcome.", event_date: null, end_date: null, price: "Free", registration_url: null, host: "Beantown Tiles", day_time: "Tuesdays 5:30pm", frequency: "weekly", beginner_friendly: true, confirmed_active_at: CA, tier: "free", created_at: ON },
  { id: "demo-e27", event_name: "New England Fall Classic", event_type: "tournament", city: "Worcester", state: "MA", venue: "DCU Center", address: null, description: "Regional fall tournament drawing players from across New England.", event_date: "2026-11-21", end_date: null, price: "$65", registration_url: "https://example.com", host: "New England Mahjong", day_time: null, frequency: "once", beginner_friendly: true, confirmed_active_at: null, tier: "free", created_at: ON },
  { id: "demo-e28", event_name: "Philadelphia Main Line Mahjong", event_type: "open_play", city: "Philadelphia", state: "PA", venue: "Radnor Library", address: null, description: "Weekly Main Line game, welcoming to newcomers.", event_date: null, end_date: null, price: "Free", registration_url: null, host: "Liberty Mahjong", day_time: "Wednesdays 10am", frequency: "weekly", beginner_friendly: true, confirmed_active_at: CA, tier: "free", created_at: ON },
  { id: "demo-e29", event_name: "Princeton Evening League", event_type: "league", city: "Princeton", state: "NJ", venue: "Princeton Public Library", address: null, description: "Ten-week evening league for working players.", event_date: null, end_date: null, price: "$40 season", registration_url: null, host: "Garden State Mahjong", day_time: "Thursdays 7pm", frequency: "weekly", beginner_friendly: false, confirmed_active_at: CA, tier: "free", created_at: ON },
  { id: "demo-e30", event_name: "Charlotte Queen City Open Play", event_type: "open_play", city: "Charlotte", state: "NC", venue: "ImaginOn", address: null, description: "Friendly weekly game, all levels.", event_date: null, end_date: null, price: "Free", registration_url: null, host: "Carolina Tiles", day_time: "Fridays 10am", frequency: "weekly", beginner_friendly: true, confirmed_active_at: CA, tier: "free", created_at: ON },
  { id: "demo-e31", event_name: "Asheville Mountain Mahjong Retreat", event_type: "retreat", city: "Asheville", state: "NC", venue: "Omni Grove Park Inn", address: null, description: "Long-weekend retreat in the Blue Ridge. Play, spa, and mountain views. Limited to 30.", event_date: "2026-09-25", end_date: "2026-09-28", price: "$575", registration_url: "https://example.com", host: "Blue Ridge Mahjong", day_time: null, frequency: "multi_day", beginner_friendly: true, confirmed_active_at: null, tier: "free", created_at: ON },
  { id: "demo-e32", event_name: "Seattle Eastside Open Play", event_type: "open_play", city: "Bellevue", state: "WA", venue: "Bellevue Library", address: null, description: "Weekly Eastside game, friendly and welcoming.", event_date: null, end_date: null, price: "Free", registration_url: null, host: "Emerald City Mahjong", day_time: "Tuesdays 1pm", frequency: "weekly", beginner_friendly: true, confirmed_active_at: CA, tier: "free", created_at: ON },
  { id: "demo-e33", event_name: "Ann Arbor Wednesday Tiles", event_type: "open_play", city: "Ann Arbor", state: "MI", venue: "AADL Downtown", address: null, description: "Weekly university-town game, all levels.", event_date: null, end_date: null, price: "Free", registration_url: null, host: "Great Lakes Mahjong", day_time: "Wednesdays 6pm", frequency: "weekly", beginner_friendly: true, confirmed_active_at: CA, tier: "free", created_at: ON },
  { id: "demo-e34", event_name: "Minneapolis Lakes Open Play", event_type: "open_play", city: "Minneapolis", state: "MN", venue: "Walker Library", address: null, description: "Twice-monthly game near the lakes.", event_date: null, end_date: null, price: "Free", registration_url: null, host: "North Star Mahjong", day_time: "2nd and 4th Tuesdays 6pm", frequency: "biweekly", beginner_friendly: true, confirmed_active_at: CA, tier: "free", created_at: ON },
  { id: "demo-e35", event_name: "Nashville Music City Tournament", event_type: "tournament", city: "Nashville", state: "TN", venue: "Music City Center", address: null, description: "One-day tournament with a beginner bracket.", event_date: "2027-02-28", end_date: null, price: "$55", registration_url: "https://example.com", host: "Tennessee Mahjong", day_time: null, frequency: "once", beginner_friendly: true, confirmed_active_at: null, tier: "free", created_at: ON },
  { id: "demo-e36", event_name: "Arlington Beginners Class", event_type: "class", city: "Arlington", state: "VA", venue: "Central Library", address: null, description: "Four-week beginner class covering the card, rules, and etiquette.", event_date: null, end_date: null, price: "$80 series", registration_url: "https://example.com", host: "DC Metro Mahjong", day_time: "Mondays 6pm", frequency: "weekly", beginner_friendly: true, confirmed_active_at: CA, tier: "free", created_at: ON },
  { id: "demo-e37", event_name: "Columbus Capital League", event_type: "league", city: "Columbus", state: "OH", venue: "Whetstone Library", address: null, description: "Seasonal league with standings and a finale.", event_date: null, end_date: null, price: "$30 season", registration_url: null, host: "Buckeye Mahjong", day_time: "Thursdays 6:30pm", frequency: "weekly", beginner_friendly: false, confirmed_active_at: CA, tier: "free", created_at: ON },
  { id: "demo-e38", event_name: "Alaska Mahjong Cruise", event_type: "retreat", city: "Seattle", state: "WA", venue: "Princess Cruises, Discovery Princess", address: null, description: "Seven-night organized mahjong cruise to Alaska. Daily play, lessons, and glacier views.", event_date: "2026-08-29", end_date: "2026-09-05", price: "From $1,650", registration_url: "https://example.com", host: "Mahjong at Sea", day_time: null, frequency: "multi_day", beginner_friendly: true, confirmed_active_at: null, tier: "free", created_at: ON },
];

type DemoPlayer = {
  id: string; name: string; city: string; state: string; skill_level: string;
  availability: string | null; bio: string | null; avatar_color: string;
  game_types: string[]; contact_email: string | null; status: string; created_at: string;
};

const PINK = "#e91e8c", NAVY = "#1a1f5e", GOLD = "#f5c842", GREEN = "#2ec95c";
export const demoPlayers: DemoPlayer[] = [
  { id: "demo-p1", name: "Susan R.", city: "Scottsdale", state: "AZ", skill_level: "intermediate", availability: "Weekday mornings", bio: "Looking for a regular fourth. Play NMJL, love a friendly table.", avatar_color: PINK, game_types: ["american"], contact_email: null, status: "published", created_at: ON },
  { id: "demo-p2", name: "Marcia L.", city: "Phoenix", state: "AZ", skill_level: "advanced", availability: "Evenings and weekends", bio: "Tournament player happy to mentor newer players.", avatar_color: NAVY, game_types: ["american"], contact_email: null, status: "published", created_at: ON },
  { id: "demo-p3", name: "Ellen K.", city: "Boca Raton", state: "FL", skill_level: "beginner", availability: "Sunday mornings", bio: "New to mahjong and eager to learn. Snowbird, here Nov-Apr.", avatar_color: GOLD, game_types: ["american"], contact_email: null, status: "published", created_at: ON },
  { id: "demo-p4", name: "Rhonda B.", city: "Naples", state: "FL", skill_level: "intermediate", availability: "Afternoons", bio: "Seasonal resident looking to join or start a weekly game.", avatar_color: GREEN, game_types: ["american"], contact_email: null, status: "published", created_at: ON },
  { id: "demo-p5", name: "Debbie S.", city: "Dallas", state: "TX", skill_level: "intermediate", availability: "Tuesday and Thursday mornings", bio: "Played for years in Chicago, new to Dallas and looking for a group.", avatar_color: PINK, game_types: ["american"], contact_email: null, status: "published", created_at: ON },
  { id: "demo-p6", name: "Carol T.", city: "Austin", state: "TX", skill_level: "beginner", availability: "Flexible", bio: "Just took a class and want to keep practicing with patient players.", avatar_color: NAVY, game_types: ["american"], contact_email: null, status: "published", created_at: ON },
  { id: "demo-p7", name: "Linda M.", city: "New York", state: "NY", skill_level: "advanced", availability: "Weekday lunch", bio: "Midtown player, quick games on my lunch hour.", avatar_color: GOLD, game_types: ["american"], contact_email: null, status: "published", created_at: ON },
  { id: "demo-p8", name: "Janet W.", city: "Garden City", state: "NY", skill_level: "intermediate", availability: "Weekends", bio: "Long Island player looking to expand my circle.", avatar_color: GREEN, game_types: ["american"], contact_email: null, status: "published", created_at: ON },
  { id: "demo-p9", name: "Patty H.", city: "San Mateo", state: "CA", skill_level: "beginner", availability: "Saturdays", bio: "Learning the game and loving it. Looking for a beginner-friendly group.", avatar_color: PINK, game_types: ["american"], contact_email: null, status: "published", created_at: ON },
  { id: "demo-p10", name: "Gloria D.", city: "Palm Springs", state: "CA", skill_level: "intermediate", availability: "Mornings", bio: "Desert player, year-round. Always up for a game.", avatar_color: NAVY, game_types: ["american"], contact_email: null, status: "published", created_at: ON },
  { id: "demo-p11", name: "Sandy F.", city: "Evanston", state: "IL", skill_level: "intermediate", availability: "Wednesday afternoons", bio: "North Shore regular, would love another table nearby.", avatar_color: GOLD, game_types: ["american"], contact_email: null, status: "published", created_at: ON },
  { id: "demo-p12", name: "Barbara N.", city: "Atlanta", state: "GA", skill_level: "advanced", availability: "Evenings", bio: "Competitive player, happy to host at my place.", avatar_color: GREEN, game_types: ["american"], contact_email: null, status: "published", created_at: ON },
  { id: "demo-p13", name: "Nancy P.", city: "Houston", state: "TX", skill_level: "intermediate", availability: "Weekday mornings", bio: "Looking for a steady weekly group near the Galleria.", avatar_color: PINK, game_types: ["american"], contact_email: null, status: "published", created_at: ON },
  { id: "demo-p14", name: "Sheila G.", city: "Miami", state: "FL", skill_level: "advanced", availability: "Flexible", bio: "Tournament regular, glad to teach newer players.", avatar_color: NAVY, game_types: ["american"], contact_email: null, status: "published", created_at: ON },
  { id: "demo-p15", name: "Roberta M.", city: "Sarasota", state: "FL", skill_level: "beginner", availability: "Afternoons", bio: "Recently retired and learning. Patient table, please.", avatar_color: GOLD, game_types: ["american"], contact_email: null, status: "published", created_at: ON },
  { id: "demo-p16", name: "Helen C.", city: "Los Angeles", state: "CA", skill_level: "intermediate", availability: "Mornings", bio: "Westside player looking to add a second weekly game.", avatar_color: GREEN, game_types: ["american"], contact_email: null, status: "published", created_at: ON },
  { id: "demo-p17", name: "Dorothy L.", city: "San Diego", state: "CA", skill_level: "advanced", availability: "Weekends", bio: "Competitive but friendly. Happy to host.", avatar_color: PINK, game_types: ["american"], contact_email: null, status: "published", created_at: ON },
  { id: "demo-p18", name: "Renee B.", city: "Brooklyn", state: "NY", skill_level: "beginner", availability: "Evenings", bio: "New to the game, looking for a welcoming group in Brooklyn.", avatar_color: NAVY, game_types: ["american"], contact_email: null, status: "published", created_at: ON },
  { id: "demo-p19", name: "Marjorie S.", city: "Boston", state: "MA", skill_level: "intermediate", availability: "Tuesday evenings", bio: "Back Bay player seeking a regular table.", avatar_color: GOLD, game_types: ["american"], contact_email: null, status: "published", created_at: ON },
  { id: "demo-p20", name: "Eleanor T.", city: "Philadelphia", state: "PA", skill_level: "intermediate", availability: "Weekday mornings", bio: "Main Line player, would love a few more games a month.", avatar_color: GREEN, game_types: ["american"], contact_email: null, status: "published", created_at: ON },
  { id: "demo-p21", name: "Judith R.", city: "Princeton", state: "NJ", skill_level: "advanced", availability: "Evenings", bio: "League player open to subbing and hosting.", avatar_color: PINK, game_types: ["american"], contact_email: null, status: "published", created_at: ON },
  { id: "demo-p22", name: "Anne W.", city: "Charlotte", state: "NC", skill_level: "beginner", availability: "Flexible", bio: "Just learned and eager to practice with kind players.", avatar_color: NAVY, game_types: ["american"], contact_email: null, status: "published", created_at: ON },
  { id: "demo-p23", name: "Carolyn H.", city: "Bellevue", state: "WA", skill_level: "intermediate", availability: "Tuesday afternoons", bio: "Eastside player looking to grow my circle.", avatar_color: GOLD, game_types: ["american"], contact_email: null, status: "published", created_at: ON },
  { id: "demo-p24", name: "Frances D.", city: "Ann Arbor", state: "MI", skill_level: "intermediate", availability: "Wednesdays", bio: "University-town player, friendly and consistent.", avatar_color: GREEN, game_types: ["american"], contact_email: null, status: "published", created_at: ON },
  { id: "demo-p25", name: "Lois K.", city: "Minneapolis", state: "MN", skill_level: "beginner", availability: "Mornings", bio: "Learning the game and looking for a beginner-friendly table.", avatar_color: PINK, game_types: ["american"], contact_email: null, status: "published", created_at: ON },
  { id: "demo-p26", name: "Beverly A.", city: "Nashville", state: "TN", skill_level: "intermediate", availability: "Weekends", bio: "New to Nashville, looking for players.", avatar_color: NAVY, game_types: ["american"], contact_email: null, status: "published", created_at: ON },
  { id: "demo-p27", name: "Joyce M.", city: "Arlington", state: "VA", skill_level: "beginner", availability: "Evenings", bio: "Took a class and want to keep going. DC metro area.", avatar_color: GOLD, game_types: ["american"], contact_email: null, status: "published", created_at: ON },
  { id: "demo-p28", name: "Maureen F.", city: "Columbus", state: "OH", skill_level: "advanced", availability: "Thursday evenings", bio: "League player happy to mentor and host.", avatar_color: GREEN, game_types: ["american"], contact_email: null, status: "published", created_at: ON },
];

type DemoVenue = {
  id: string; business_name: string; venue_type: string; city: string; state: string;
  address: string | null; description: string | null; website: string | null;
  instagram: string | null; display_email: string | null; logo_url: string | null;
  phone?: string | null; tier: string; created_at: string;
};

export const demoTeachers: DemoVenue[] = [
  { id: "demo-t1", business_name: "Desert Tiles Mahjong Lessons", venue_type: "Mahjong Instructor", city: "Scottsdale", state: "AZ", address: null, description: "Private and small-group American Mahjong lessons for all levels. Beginners my specialty.", website: "https://example.com", instagram: "deserttiles", display_email: "hello@example.com", logo_url: null, phone: "702-555-0148", tier: "pro", created_at: ON },
  { id: "demo-t2", business_name: "Gulf Coast Mahjong School", venue_type: "Mahjong Instructor", city: "Naples", state: "FL", address: null, description: "Learn to play in four weeks. Card reading, strategy, and confidence at the table.", website: "https://example.com", instagram: "gulfcoastmahj", display_email: "play@example.com", logo_url: null, tier: "pro", created_at: ON },
  { id: "demo-t3", business_name: "Boca Mahj Studio", venue_type: "studio", city: "Boca Raton", state: "FL", address: null, description: "Lessons, refreshers, and corporate mahjong events in South Florida.", website: null, instagram: "bocamahj", display_email: "info@example.com", logo_url: null, tier: "free", created_at: ON },
  { id: "demo-t4", business_name: "Big D Mahjong Lessons", venue_type: "Mahjong Instructor", city: "Dallas", state: "TX", address: null, description: "Patient, friendly instruction. Host your own group lesson at home or at my studio.", website: "https://example.com", instagram: "bigdmahjong", display_email: "teach@example.com", logo_url: null, phone: "214-555-0172", tier: "pro", created_at: ON },
  { id: "demo-t5", business_name: "Golden Gate Mahjong Classes", venue_type: "class", city: "San Mateo", state: "CA", address: null, description: "Beginner series and intermediate workshops on the Peninsula.", website: "https://example.com", instagram: "ggmahjong", display_email: "learn@example.com", logo_url: null, tier: "free", created_at: ON },
  { id: "demo-t6", business_name: "NYC Mahjong Lessons", venue_type: "Mahjong Instructor", city: "New York", state: "NY", address: null, description: "In-home and virtual lessons across Manhattan and Brooklyn.", website: "https://example.com", instagram: "nycmahjong", display_email: "play@example.com", logo_url: null, phone: "212-555-0190", tier: "pro", created_at: ON },
  { id: "demo-t7", business_name: "Peach State Mahjong Academy", venue_type: "school", city: "Atlanta", state: "GA", address: null, description: "Group classes, private coaching, and tournament prep.", website: null, instagram: "peachmahj", display_email: "hello@example.com", logo_url: null, tier: "free", created_at: ON },
  { id: "demo-t8", business_name: "North Shore Mahjong Lessons", venue_type: "Mahjong Instructor", city: "Evanston", state: "IL", address: null, description: "Learn the current card with a relaxed, encouraging teacher.", website: "https://example.com", instagram: null, display_email: "info@example.com", logo_url: null, tier: "free", created_at: ON },
  { id: "demo-t9", business_name: "Bayou Tiles Mahjong Lessons", venue_type: "Mahjong Instructor", city: "Houston", state: "TX", address: null, description: "Private and group lessons across greater Houston. Beginners welcome.", website: "https://example.com", instagram: "bayoutiles", display_email: "play@example.com", logo_url: null, tier: "pro", created_at: ON },
  { id: "demo-t10", business_name: "Suncoast Mahjong School", venue_type: "school", city: "Sarasota", state: "FL", address: null, description: "Beginner series, refreshers, and private coaching on the Gulf Coast.", website: null, instagram: "suncoastmahj", display_email: "learn@example.com", logo_url: null, tier: "free", created_at: ON },
  { id: "demo-t11", business_name: "LA Mahjong Lessons", venue_type: "Mahjong Instructor", city: "Los Angeles", state: "CA", address: null, description: "In-home and virtual lessons across the Westside and the Valley.", website: "https://example.com", instagram: "lamahjong", display_email: "hello@example.com", logo_url: null, tier: "pro", created_at: ON },
  { id: "demo-t12", business_name: "San Diego Mahjong Studio", venue_type: "studio", city: "San Diego", state: "CA", address: null, description: "Lessons, open play, and corporate events near the coast.", website: "https://example.com", instagram: "sdmahjong", display_email: "info@example.com", logo_url: null, tier: "free", created_at: ON },
  { id: "demo-t13", business_name: "Brooklyn Mahjong Lessons", venue_type: "Mahjong Instructor", city: "Brooklyn", state: "NY", address: null, description: "Patient, beginner-focused lessons in brownstone Brooklyn.", website: "https://example.com", instagram: "bkmahjong", display_email: "play@example.com", logo_url: null, tier: "pro", created_at: ON },
  { id: "demo-t14", business_name: "Beantown Mahjong Academy", venue_type: "school", city: "Boston", state: "MA", address: null, description: "Group classes and tournament prep in the Boston area.", website: "https://example.com", instagram: "beantownmahj", display_email: "learn@example.com", logo_url: null, tier: "free", created_at: ON },
  { id: "demo-t15", business_name: "Liberty Mahjong Lessons", venue_type: "Mahjong Instructor", city: "Philadelphia", state: "PA", address: null, description: "Main Line and center city lessons for all levels.", website: "https://example.com", instagram: "libertymahj", display_email: "hello@example.com", logo_url: null, tier: "free", created_at: ON },
  { id: "demo-t16", business_name: "Carolina Tiles Lessons", venue_type: "Mahjong Instructor", city: "Charlotte", state: "NC", address: null, description: "Friendly beginner lessons and group classes in the Queen City.", website: "https://example.com", instagram: "carolinatiles", display_email: "play@example.com", logo_url: null, tier: "pro", created_at: ON },
  { id: "demo-t17", business_name: "Emerald City Mahjong School", venue_type: "school", city: "Bellevue", state: "WA", address: null, description: "Beginner workshops and intermediate clinics on the Eastside.", website: "https://example.com", instagram: "emeraldmahj", display_email: "learn@example.com", logo_url: null, tier: "free", created_at: ON },
  { id: "demo-t18", business_name: "Great Lakes Mahjong Lessons", venue_type: "Mahjong Instructor", city: "Ann Arbor", state: "MI", address: null, description: "Relaxed lessons for university-town players, all ages.", website: null, instagram: null, display_email: "info@example.com", logo_url: null, tier: "free", created_at: ON },
  { id: "demo-t19", business_name: "DC Metro Mahjong Classes", venue_type: "class", city: "Arlington", state: "VA", address: null, description: "Four-week beginner classes and private coaching in the DC area.", website: "https://example.com", instagram: "dcmahjong", display_email: "hello@example.com", logo_url: null, tier: "pro", created_at: ON },
  { id: "demo-t20", business_name: "Music City Mahjong Lessons", venue_type: "Mahjong Instructor", city: "Nashville", state: "TN", address: null, description: "Learn the current card with a warm, encouraging teacher.", website: "https://example.com", instagram: "musiccitymahj", display_email: "play@example.com", logo_url: null, tier: "free", created_at: ON },
];

type DemoCruisePost = {
  id: string; name: string; cruise_line: string; ship: string | null;
  depart_date: string; return_date: string | null; skill_level: string | null;
};

export const demoCruisePosts: DemoCruisePost[] = [
  { id: "demo-c1", name: "Maureen", cruise_line: "Royal Caribbean", ship: "Symphony of the Seas", depart_date: "2026-08-15", return_date: "2026-08-22", skill_level: "intermediate" },
  { id: "demo-c2", name: "Joan", cruise_line: "Celebrity", ship: "Celebrity Beyond", depart_date: "2026-09-20", return_date: "2026-09-27", skill_level: "advanced" },
  { id: "demo-c3", name: "Phyllis", cruise_line: "Princess", ship: "Sky Princess", depart_date: "2026-10-10", return_date: "2026-10-17", skill_level: "beginner" },
  { id: "demo-c4", name: "Roberta", cruise_line: "Holland America", ship: "Koningsdam", depart_date: "2026-11-14", return_date: "2026-11-24", skill_level: "intermediate" },
  { id: "demo-c5", name: "Sharon", cruise_line: "Norwegian", ship: "Norwegian Joy", depart_date: "2027-01-10", return_date: "2027-01-17", skill_level: "intermediate" },
  { id: "demo-c6", name: "Diane", cruise_line: "Carnival", ship: "Carnival Celebration", depart_date: "2027-02-08", return_date: "2027-02-15", skill_level: "beginner" },
  { id: "demo-c7", name: "Carol", cruise_line: "Princess", ship: "Discovery Princess", depart_date: "2026-08-29", return_date: "2026-09-05", skill_level: "intermediate" },
  { id: "demo-c8", name: "Lois", cruise_line: "Viking", ship: "Viking Star", depart_date: "2026-09-12", return_date: "2026-09-26", skill_level: "advanced" },
  { id: "demo-c9", name: "Marlene", cruise_line: "Celebrity", ship: "Celebrity Ascent", depart_date: "2026-10-25", return_date: "2026-11-01", skill_level: "beginner" },
  { id: "demo-c10", name: "Gail", cruise_line: "Royal Caribbean", ship: "Wonder of the Seas", depart_date: "2026-12-06", return_date: "2026-12-13", skill_level: "intermediate" },
  { id: "demo-c11", name: "Susan", cruise_line: "Holland America", ship: "Rotterdam", depart_date: "2027-01-24", return_date: "2027-02-03", skill_level: "intermediate" },
  { id: "demo-c12", name: "Ellen", cruise_line: "Norwegian", ship: "Norwegian Viva", depart_date: "2027-03-07", return_date: "2027-03-14", skill_level: "beginner" },
];

export const demoForming: { share_code: string; day_of_week: string | null; time_of_day: string | null; city: string | null; total: number; filled: number }[] = [
  { share_code: "demo-f1", day_of_week: "Tuesday", time_of_day: "Morning", city: "Scottsdale, AZ", total: 4, filled: 3 },
  { share_code: "demo-f2", day_of_week: "Wednesday", time_of_day: "Afternoon", city: "Dallas, TX", total: 4, filled: 2 },
  { share_code: "demo-f3", day_of_week: "Thursday", time_of_day: "Evening", city: "Boca Raton, FL", total: 4, filled: 3 },
  { share_code: "demo-f4", day_of_week: "Sunday", time_of_day: "Morning", city: "New York, NY", total: 4, filled: 2 },
  { share_code: "demo-f5", day_of_week: "Monday", time_of_day: "Afternoon", city: "Evanston, IL", total: 4, filled: 3 },
  { share_code: "demo-f6", day_of_week: "Saturday", time_of_day: "Morning", city: "San Mateo, CA", total: 4, filled: 2 },
  { share_code: "demo-f7", day_of_week: "Tuesday", time_of_day: "Afternoon", city: "Houston, TX", total: 4, filled: 3 },
  { share_code: "demo-f8", day_of_week: "Wednesday", time_of_day: "Morning", city: "Los Angeles, CA", total: 4, filled: 2 },
  { share_code: "demo-f9", day_of_week: "Thursday", time_of_day: "Evening", city: "Boston, MA", total: 4, filled: 3 },
  { share_code: "demo-f10", day_of_week: "Friday", time_of_day: "Morning", city: "Charlotte, NC", total: 4, filled: 2 },
  { share_code: "demo-f11", day_of_week: "Sunday", time_of_day: "Afternoon", city: "Philadelphia, PA", total: 4, filled: 3 },
  { share_code: "demo-f12", day_of_week: "Saturday", time_of_day: "Morning", city: "Seattle, WA", total: 4, filled: 2 },
];

// Map counts derived from the demo rows so states light up on the homepage map.
export const demoStateCounts: Record<string, { players: number; events: number; venues: number }> = (() => {
  const c: Record<string, { players: number; events: number; venues: number }> = {};
  const bump = (st: string, key: "players" | "events" | "venues") => {
    const a = (st || "").toUpperCase();
    if (!a) return;
    (c[a] ||= { players: 0, events: 0, venues: 0 })[key]++;
  };
  demoPlayers.forEach((p) => bump(p.state, "players"));
  demoEvents.forEach((e) => bump(e.state, "events"));
  demoTeachers.forEach((t) => bump(t.state, "venues"));
  return c;
})();
