export interface StateData {
  name: string;
  abbr: string;
  slug: string;
  cities: string[];
  nearby: string[];
  desc: string;
}

export const STATES: Record<string, StateData> = {
  alabama: { name: "Alabama", abbr: "AL", slug: "alabama", cities: ["Birmingham","Huntsville","Mobile","Montgomery","Tuscaloosa","Hoover"], nearby: ["Mississippi","Tennessee","Georgia","Florida"], desc: "Find players, groups, open plays and events across Alabama." },
  alaska: { name: "Alaska", abbr: "AK", slug: "alaska", cities: ["Anchorage","Fairbanks","Juneau","Wasilla","Sitka"], nearby: ["Washington","Hawaii"], desc: "Find players, groups, open plays and events across Alaska." },
  arizona: { name: "Arizona", abbr: "AZ", slug: "arizona", cities: ["Phoenix","Scottsdale","Tucson","Mesa","Chandler","Tempe","Sedona","Flagstaff"], nearby: ["Nevada","California","New Mexico","Utah","Colorado"], desc: "Find players, groups, open plays and events across Arizona — from Phoenix to Scottsdale and everywhere in between." },
  arkansas: { name: "Arkansas", abbr: "AR", slug: "arkansas", cities: ["Little Rock","Fayetteville","Fort Smith","Bentonville","Hot Springs"], nearby: ["Missouri","Tennessee","Mississippi","Louisiana","Texas","Oklahoma"], desc: "Find players, groups, open plays and events across Arkansas." },
  california: { name: "California", abbr: "CA", slug: "california", cities: ["Los Angeles","San Francisco","San Diego","Palm Springs","Sacramento","San Jose","Irvine","Beverly Hills","Santa Monica","Pasadena"], nearby: ["Nevada","Arizona","Oregon"], desc: "Find players, groups, open plays and events across California — from LA to San Francisco and everywhere in between." },
  colorado: { name: "Colorado", abbr: "CO", slug: "colorado", cities: ["Denver","Boulder","Colorado Springs","Fort Collins","Aurora","Lakewood","Vail"], nearby: ["Utah","Wyoming","Nebraska","Kansas","New Mexico","Arizona"], desc: "Find players, groups, open plays and events across Colorado." },
  connecticut: { name: "Connecticut", abbr: "CT", slug: "connecticut", cities: ["Hartford","New Haven","Stamford","Bridgeport","Greenwich","Westport"], nearby: ["New York","Massachusetts","Rhode Island"], desc: "Find players, groups, open plays and events across Connecticut." },
  delaware: { name: "Delaware", abbr: "DE", slug: "delaware", cities: ["Wilmington","Dover","Newark","Rehoboth Beach"], nearby: ["Maryland","Pennsylvania","New Jersey"], desc: "Find players, groups, open plays and events across Delaware." },
  florida: { name: "Florida", abbr: "FL", slug: "florida", cities: ["Miami","Boca Raton","Orlando","Tampa","Naples","Fort Lauderdale","Palm Beach","Sarasota","Jacksonville"], nearby: ["Georgia","Alabama","South Carolina"], desc: "Find players, groups, open plays and events across Florida — from Miami to Jacksonville and everywhere in between." },
  georgia: { name: "Georgia", abbr: "GA", slug: "georgia", cities: ["Atlanta","Savannah","Augusta","Athens","Marietta","Roswell"], nearby: ["Florida","South Carolina","North Carolina","Tennessee","Alabama"], desc: "Find players, groups, open plays and events across Georgia." },
  hawaii: { name: "Hawaii", abbr: "HI", slug: "hawaii", cities: ["Honolulu","Maui","Kailua","Hilo","Pearl City"], nearby: ["California","Alaska"], desc: "Find players, groups, open plays and events across Hawaii." },
  idaho: { name: "Idaho", abbr: "ID", slug: "idaho", cities: ["Boise","Idaho Falls","Meridian","Nampa","Coeur d'Alene"], nearby: ["Montana","Wyoming","Utah","Nevada","Oregon","Washington"], desc: "Find players, groups, open plays and events across Idaho." },
  illinois: { name: "Illinois", abbr: "IL", slug: "illinois", cities: ["Chicago","Evanston","Naperville","Springfield","Schaumburg","Oak Park","Skokie"], nearby: ["Indiana","Wisconsin","Iowa","Missouri","Kentucky"], desc: "Find players, groups, open plays and events across Illinois — from Chicago to Naperville and everywhere in between." },
  indiana: { name: "Indiana", abbr: "IN", slug: "indiana", cities: ["Indianapolis","Fort Wayne","Bloomington","Carmel","Fishers"], nearby: ["Illinois","Ohio","Michigan","Kentucky"], desc: "Find players, groups, open plays and events across Indiana." },
  iowa: { name: "Iowa", abbr: "IA", slug: "iowa", cities: ["Des Moines","Cedar Rapids","Iowa City","Davenport","Ames"], nearby: ["Minnesota","Wisconsin","Illinois","Missouri","Nebraska","South Dakota"], desc: "Find players, groups, open plays and events across Iowa." },
  kansas: { name: "Kansas", abbr: "KS", slug: "kansas", cities: ["Kansas City","Wichita","Overland Park","Topeka","Olathe"], nearby: ["Missouri","Nebraska","Colorado","Oklahoma"], desc: "Find players, groups, open plays and events across Kansas." },
  kentucky: { name: "Kentucky", abbr: "KY", slug: "kentucky", cities: ["Louisville","Lexington","Bowling Green","Covington","Frankfort"], nearby: ["Tennessee","Virginia","West Virginia","Ohio","Indiana","Illinois","Missouri"], desc: "Find players, groups, open plays and events across Kentucky." },
  louisiana: { name: "Louisiana", abbr: "LA", slug: "louisiana", cities: ["New Orleans","Baton Rouge","Shreveport","Lafayette","Metairie"], nearby: ["Mississippi","Arkansas","Texas"], desc: "Find players, groups, open plays and events across Louisiana." },
  maine: { name: "Maine", abbr: "ME", slug: "maine", cities: ["Portland","Bangor","Augusta","Lewiston","Kennebunkport"], nearby: ["New Hampshire","Vermont","Massachusetts"], desc: "Find players, groups, open plays and events across Maine." },
  maryland: { name: "Maryland", abbr: "MD", slug: "maryland", cities: ["Baltimore","Bethesda","Rockville","Annapolis","Silver Spring","Columbia"], nearby: ["Virginia","Pennsylvania","Delaware","West Virginia"], desc: "Find players, groups, open plays and events across Maryland." },
  massachusetts: { name: "Massachusetts", abbr: "MA", slug: "massachusetts", cities: ["Boston","Cambridge","Newton","Brookline","Worcester","Springfield","Cape Cod"], nearby: ["Connecticut","Rhode Island","New Hampshire","Vermont","New York"], desc: "Find players, groups, open plays and events across Massachusetts." },
  michigan: { name: "Michigan", abbr: "MI", slug: "michigan", cities: ["Detroit","Ann Arbor","Grand Rapids","Lansing","Troy","Birmingham","West Bloomfield"], nearby: ["Ohio","Indiana","Wisconsin"], desc: "Find players, groups, open plays and events across Michigan." },
  minnesota: { name: "Minnesota", abbr: "MN", slug: "minnesota", cities: ["Minneapolis","St. Paul","Edina","Bloomington","Rochester","Duluth"], nearby: ["Wisconsin","Iowa","North Dakota","South Dakota"], desc: "Find players, groups, open plays and events across Minnesota." },
  mississippi: { name: "Mississippi", abbr: "MS", slug: "mississippi", cities: ["Jackson","Biloxi","Gulfport","Hattiesburg","Oxford"], nearby: ["Alabama","Louisiana","Tennessee","Arkansas"], desc: "Find players, groups, open plays and events across Mississippi." },
  missouri: { name: "Missouri", abbr: "MO", slug: "missouri", cities: ["St. Louis","Kansas City","Springfield","Columbia","Independence"], nearby: ["Illinois","Kansas","Iowa","Arkansas","Tennessee","Kentucky","Nebraska","Oklahoma"], desc: "Find players, groups, open plays and events across Missouri." },
  montana: { name: "Montana", abbr: "MT", slug: "montana", cities: ["Billings","Missoula","Great Falls","Bozeman","Helena"], nearby: ["North Dakota","South Dakota","Wyoming","Idaho"], desc: "Find players, groups, open plays and events across Montana." },
  nebraska: { name: "Nebraska", abbr: "NE", slug: "nebraska", cities: ["Omaha","Lincoln","Grand Island","Bellevue","Kearney"], nearby: ["Iowa","South Dakota","Wyoming","Colorado","Kansas","Missouri"], desc: "Find players, groups, open plays and events across Nebraska." },
  nevada: { name: "Nevada", abbr: "NV", slug: "nevada", cities: ["Las Vegas","Summerlin","Henderson","North Las Vegas","Reno","Boulder City","Sparks"], nearby: ["California","Arizona","Utah","Oregon","Idaho"], desc: "Find players, groups, open plays and events across Nevada — from Las Vegas to Sparks and everywhere in between." },
  "new-hampshire": { name: "New Hampshire", abbr: "NH", slug: "new-hampshire", cities: ["Manchester","Nashua","Concord","Portsmouth","Hanover"], nearby: ["Vermont","Maine","Massachusetts"], desc: "Find players, groups, open plays and events across New Hampshire." },
  "new-jersey": { name: "New Jersey", abbr: "NJ", slug: "new-jersey", cities: ["Newark","Jersey City","Princeton","Cherry Hill","Hoboken","Morristown","Tenafly"], nearby: ["New York","Pennsylvania","Delaware"], desc: "Find players, groups, open plays and events across New Jersey." },
  "new-mexico": { name: "New Mexico", abbr: "NM", slug: "new-mexico", cities: ["Albuquerque","Santa Fe","Las Cruces","Rio Rancho","Taos"], nearby: ["Arizona","Colorado","Texas","Oklahoma","Utah"], desc: "Find players, groups, open plays and events across New Mexico." },
  "new-york": { name: "New York", abbr: "NY", slug: "new-york", cities: ["New York City","Long Island","Westchester","Buffalo","Albany","Syracuse","White Plains","Scarsdale"], nearby: ["New Jersey","Connecticut","Pennsylvania","Massachusetts","Vermont"], desc: "Find players, groups, open plays and events across New York — from NYC to Long Island and everywhere in between." },
  "north-carolina": { name: "North Carolina", abbr: "NC", slug: "north-carolina", cities: ["Charlotte","Raleigh","Durham","Chapel Hill","Asheville","Greensboro","Wilmington"], nearby: ["South Carolina","Virginia","Tennessee","Georgia"], desc: "Find players, groups, open plays and events across North Carolina." },
  "north-dakota": { name: "North Dakota", abbr: "ND", slug: "north-dakota", cities: ["Fargo","Bismarck","Grand Forks","Minot"], nearby: ["South Dakota","Montana","Minnesota"], desc: "Find players, groups, open plays and events across North Dakota." },
  ohio: { name: "Ohio", abbr: "OH", slug: "ohio", cities: ["Columbus","Cleveland","Cincinnati","Toledo","Akron","Dayton","Beachwood"], nearby: ["Michigan","Indiana","Kentucky","West Virginia","Pennsylvania"], desc: "Find players, groups, open plays and events across Ohio." },
  oklahoma: { name: "Oklahoma", abbr: "OK", slug: "oklahoma", cities: ["Oklahoma City","Tulsa","Norman","Edmond","Broken Arrow"], nearby: ["Texas","Kansas","Arkansas","Missouri","Colorado","New Mexico"], desc: "Find players, groups, open plays and events across Oklahoma." },
  oregon: { name: "Oregon", abbr: "OR", slug: "oregon", cities: ["Portland","Eugene","Salem","Bend","Lake Oswego"], nearby: ["Washington","California","Idaho","Nevada"], desc: "Find players, groups, open plays and events across Oregon." },
  pennsylvania: { name: "Pennsylvania", abbr: "PA", slug: "pennsylvania", cities: ["Philadelphia","Pittsburgh","Harrisburg","Allentown","King of Prussia","Bala Cynwyd"], nearby: ["New York","New Jersey","Ohio","Delaware","Maryland","West Virginia"], desc: "Find players, groups, open plays and events across Pennsylvania." },
  "rhode-island": { name: "Rhode Island", abbr: "RI", slug: "rhode-island", cities: ["Providence","Newport","Warwick","Cranston"], nearby: ["Massachusetts","Connecticut"], desc: "Find players, groups, open plays and events across Rhode Island." },
  "south-carolina": { name: "South Carolina", abbr: "SC", slug: "south-carolina", cities: ["Charleston","Columbia","Greenville","Myrtle Beach","Hilton Head"], nearby: ["North Carolina","Georgia"], desc: "Find players, groups, open plays and events across South Carolina." },
  "south-dakota": { name: "South Dakota", abbr: "SD", slug: "south-dakota", cities: ["Sioux Falls","Rapid City","Aberdeen","Brookings"], nearby: ["North Dakota","Montana","Wyoming","Nebraska","Iowa","Minnesota"], desc: "Find players, groups, open plays and events across South Dakota." },
  tennessee: { name: "Tennessee", abbr: "TN", slug: "tennessee", cities: ["Nashville","Memphis","Knoxville","Chattanooga","Franklin"], nearby: ["Kentucky","Virginia","North Carolina","Georgia","Alabama","Mississippi","Arkansas","Missouri"], desc: "Find players, groups, open plays and events across Tennessee." },
  texas: { name: "Texas", abbr: "TX", slug: "texas", cities: ["Houston","Dallas","Austin","San Antonio","Fort Worth","Plano","Frisco","The Woodlands","Sugar Land"], nearby: ["Oklahoma","Arkansas","Louisiana","New Mexico"], desc: "Find players, groups, open plays and events across Texas — from Houston to Dallas and everywhere in between." },
  utah: { name: "Utah", abbr: "UT", slug: "utah", cities: ["Salt Lake City","Park City","Provo","Ogden","St. George"], nearby: ["Nevada","Colorado","Wyoming","Idaho","Arizona","New Mexico"], desc: "Find players, groups, open plays and events across Utah." },
  vermont: { name: "Vermont", abbr: "VT", slug: "vermont", cities: ["Burlington","Montpelier","Stowe","Brattleboro"], nearby: ["New Hampshire","Massachusetts","New York"], desc: "Find players, groups, open plays and events across Vermont." },
  virginia: { name: "Virginia", abbr: "VA", slug: "virginia", cities: ["Richmond","Virginia Beach","Arlington","Alexandria","Fairfax","Charlottesville","McLean"], nearby: ["Maryland","North Carolina","West Virginia","Kentucky","Tennessee"], desc: "Find players, groups, open plays and events across Virginia." },
  washington: { name: "Washington", abbr: "WA", slug: "washington", cities: ["Seattle","Bellevue","Tacoma","Spokane","Kirkland","Redmond","Olympia"], nearby: ["Oregon","Idaho"], desc: "Find players, groups, open plays and events across Washington." },
  "west-virginia": { name: "West Virginia", abbr: "WV", slug: "west-virginia", cities: ["Charleston","Morgantown","Huntington","Wheeling"], nearby: ["Virginia","Ohio","Pennsylvania","Kentucky","Maryland"], desc: "Find players, groups, open plays and events across West Virginia." },
  wisconsin: { name: "Wisconsin", abbr: "WI", slug: "wisconsin", cities: ["Milwaukee","Madison","Green Bay","Brookfield","Waukesha"], nearby: ["Minnesota","Iowa","Illinois","Michigan"], desc: "Find players, groups, open plays and events across Wisconsin." },
  wyoming: { name: "Wyoming", abbr: "WY", slug: "wyoming", cities: ["Cheyenne","Casper","Jackson","Laramie","Sheridan"], nearby: ["Montana","South Dakota","Nebraska","Colorado","Utah","Idaho"], desc: "Find players, groups, open plays and events across Wyoming." },
};

export const ALL_STATE_SLUGS = Object.keys(STATES);
